### PR TITLE
Add chat_models

### PR DESCRIPTION
**Pull request by riya-amemiya**
Modified code to accommodate api updates

<https://openai.com/blog/function-calling-and-other-api-updates>

### CODE REVIEW

**Comment by elias-sundqvist** [comment]
You're missing a comma on line 68 
image


Also, it seems like something more is needed to make gpt-3.5-turbo-16k work.  The below prompt works with the regular model but not the 16k version. 

image
image

**Comment by riya-amemiya** [comment]
> You're missing a comma on line 68

This error has been corrected.

>Also, it seems like something more is needed to make gpt-3.5-turbo-16k work. The below prompt works with the regular model but not the 16k version.

This problem was not reproduced in my environment.

スクリーンショット 2023-06-14 19 16 01


スクリーンショット 2023-06-14 19 15 45

**Comment by nc** [comment]
Would be great to get this merged in so we can play with functions :)

**Comment by slundberg** [comment]
Thank you so much for patching this! There were two PRs to address this problem and I merged the one based on Regex since it will be more future proof when new checkpoints come out. Closing this, but let me know if I missed something with the other PR. (the fix will hit PyPI on 0.0.63)

**Pull request closed without merging**
